### ISSUE TITLE
Cross-linking more module information

### ISSUE THREAD

**Issue by Byron** [chhantyal/py3readiness#11]
Currently when clicking a package name, one will reach the respective pypi project page.
However, when using py3readyness, I felt like I want to know more - for example how much downloads the other packages have, just to see how much is needed to rise up the charts.

Some research later I found the [PyPI Ranking](http://pypi-ranking.info) site which seems to have all the (even historical information) I wanted.

Personally I feel that py3readyness is just right in terms of simplicity, and if an additional link is added per package, it should be done so without adding clutter.

Maybe it would already help to just link the main PyPI Ranking page to the text saying "Python 3 support graph for 360 most popular Python packages!" right at the pages top.

Thanks for sharing your opinion about this.

**Comment by chhantyal** [comment]
Thanks for your suggestion.

This site is merely to check which popular libraries support Python 3 and which don't.  I understand your curiosity to check actual download stat. While generally popular libraries have higher download count, the download count number itself is affected by various factors and not correct.  See this thread https://mail.python.org/pipermail/distutils-sig/2013-May/020855.html

Also I think if we want to rise up just by increasing download count, this can lead to negative consequence like people using bot to increase download count etc (I don't expect responsible devs to do so, but you never know. It's open internet.)

Thus we should not give download count too much importance.

**Comment by Byron** [comment]
I do agree, that day I got a bit carried away as well, seeing nothing more than numbers ;).
Thanks again.
