### ISSUE TITLE
futures package is gray, but it is a backport from Python 3

### ISSUE THREAD

**Issue by ilevkivskyi** [chhantyal/py3readiness#16]
`futures` package https://pypi.python.org/pypi/futures is gray, but it is actually a backport from Python 3. IMO it either should be shown green or removed from the list.

**Comment by henryiii** [comment]
This seems to have been fixed...

**Comment by waldyrious** [comment]
Cross-referencing https://github.com/ubershmekel/python3wos/issues/11, for the record.

**Comment by chhantyal** [comment]
It is fixed.

For reference, see this PR https://github.com/brettcannon/caniusepython3/pull/98
