### ISSUE TITLE
certifi should be marked as Python 3 capable

### ISSUE THREAD

**Issue by kivikakk** [chhantyal/py3readiness#19]
This seems important (?)/relevant, as it's package number 9 on the list!

I've verified this by:

1. installing certifi on Python 3.4 (successfully), and
2. checking the PyPI package metadata (it's listed under `Classifier: Programming Language :: Python :: 3.0`, all the way up to `3.4`).

**Comment by chhantyal** [comment]
Thanks for report. Actually, Py3 is not mentioned on metadata https://pypi.python.org/pypi/certifi

We can still override though.

**Comment by chhantyal** [comment]
Certifi is green now http://py3readiness.org/. Thanks for the report.

**Comment by kivikakk** [comment]
Hooray!
