### ISSUE TITLE
2 dead links

### ISSUE THREAD

**Issue by nickjacobson** [chhantyal/py3readiness#27]
1. The link to Werkzeug on http://py3readiness.org/ is https://pypi.python.org/pypi/Werkzeug which currently gives a 404 not found error.
Here is a link that works: https://pypi.python.org/pypi/Werkzeug/0.10.1
It is listed in white on py3readiness, but on the working link it lists "Programming Language :: Python :: 3"

2. The link on py3readiness for https://pypi.python.org/pypi/marionette-transport is a dead link. A working link is https://pypi.python.org/pypi/marionette-transport/0.1

**Comment by nickjacobson** [comment]
The Werkzeug link is fixed and is now in green.

This link https://groups.google.com/forum/#!topic/mozilla.tools.marionette/K17T18rlmHU says that marionette-transport link is deprecated. That could be why its page is a dead link. Perhaps it could be removed from the py3readiness list.

**Comment by chhantyal** [comment]
Thanks for updates.
If it is deprecated, we could just flag the package here https://github.com/chhantyal/py3readiness/blob/master/flags.py

That way, we ignore this package in our graph.

**Comment by nickjacobson** [comment]
Cool. In fact the 7th post in the thread states it explicitly. "This has now landed on inbound, and the marionette-transport package is henceforth deprecated."

https://groups.google.com/d/msg/mozilla.tools.marionette/K17T18rlmHU/08ixZN3QDwAJ

So it makes sense to add it to flags.py.

**Comment by nickjacobson** [comment]
btw I think that manifestparser belongs in flags.py as well. It is part of the "moz" suite of software that is listed in flags.py. See http://mozbase.readthedocs.io/en/latest/
