### ISSUE TITLE
3 libraries that already support Python 3

### ISSUE THREAD

**Issue by nickjacobson** [chhantyal/py3readiness#29]
These 2 libraries already support Python 3 but are shown in white on http://py3readiness.org:

1. https://pypi.python.org/pypi/testresources
2. https://pypi.python.org/pypi/filechunkio

They both have the trove classifier:
"Programming Language :: Python :: 3"

I noticed that the website https://caniusepython3.com is getting their Python 3 status wrong. But if you install the `caniusepython3` library itself and check them, it returns True for their Python 3 status. So it's only the https://caniusepython3.com website that's wrong.

**Comment by nickjacobson** [comment]
It seems like this is an issue for caniusepython3.

**Comment by nickjacobson** [comment]
It's odd. If I run this:

```
>>> from caniusepython3.pypi import all_py3_projects
>>> print(all_py3_projects())
```

just like in the py3readiness/utils.py file, it does include testresources and filechunkio in the list.

**Comment by nickjacobson** [comment]
A third library is also supported by Python 3 but is in white on py3readiness.

`ipaddr` has a forked version in Python 3: https://docs.python.org/3/library/ipaddress.html

This has been added to https://github.com/brettcannon/caniusepython3/blob/master/caniusepython3/overrides.json

**Comment by chhantyal** [comment]
Thanks for the report. Actually we have update issue, that I just noticed site hasn't been updated since 15 June - looks like there is some changes in response we get from PyPI. We need to look into that.

If you want to try on local, just clone and run `python generate.py` which creates static html file.

**Comment by chhantyal** [comment]
Fixed. They are now green :)
