### ISSUE TITLE
PyPI API removal of top_packages

### ISSUE THREAD

**Issue by hugovk** [chhantyal/py3readiness#42]
Cross-posting from https://github.com/meshy/pythonwheels/issues/94:

---

Download counts are being removed from PyPI and instead BigQuery needs to be used.

See https://github.com/pypa/warehouse/pull/2480 which removes the `top_packages` from the API.

Right now, PyPI is running from https://github.com/pypa/pypi-legacy but will be switching to https://github.com/pypa/warehouse soon. (Their [milestones](https://github.com/pypa/warehouse/milestones) show they're 95% complete to launch, and 38% complete to shut down legacy PyPI.)

See https://github.com/badges/shields/issues/716 and https://github.com/zhmcclient/python-zhmcclient/pull/73 for some more info on BigQuery.

---

Perhaps in the short term Python 3 readiness could use a hardcoded list of the top 360 packages.

**Comment by chhantyal** [comment]
Yes, top packages don't seem to change often.
We could, as you suggested, use hardcoded list.
