### ISSUE TITLE
Show packages that do not support Python 2?

### ISSUE THREAD

**Issue by stsievert** [chhantyal/py3readiness#45]
I'd like to see a visualization of which latest releases only support Python 3 (and do not support Python 2). i.e., NumPy will not support Python 2 after Jan. 1, 2019 ([source]). I'd like to see a representation of that.

[source]:https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

**Comment by chhantyal** [comment]
Thanks for request. I think it is out of scope for this project.

However, there is something similar https://hugovk.github.io/drop-python/

@hugovk
