### ISSUE TITLE
M2Crypto and diamond supports python3

### ISSUE THREAD

**Issue by rahul-gj** [chhantyal/py3readiness#47]
M2Crypto and diamond  support python3 but on website it doesn't show it. Please update. I am new to git don't know how to do edits.

**Comment by hugovk** [comment]
# M2Crypto

http://py3readiness.org/ says "Last updated Saturday, 20 January 2018, 10:57:58 . (Updated daily.)"

Looks like the daily updates have broken.

---


```console
$ caniusepython3 --projects M2Crypto
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!
```

M2Crypro has recently added [Python 3 compatibility](https://gitlab.com/m2crypto/m2crypto/merge_requests/65) and the last release was [2018-02-23](https://pypi.python.org/pypi/M2Crypto), so I expect it will be picked up the next time py3readiness runs.

**Comment by hugovk** [comment]
# diamond

```console
$ caniusepython3 --projects diamond
Finding and checking dependencies ...

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  diamond
```

diamond doesn't yet declare Python 3 support: 
* https://pypi.python.org/pypi/diamond

And it doesn't look like they support Python 3 yet:
* https://github.com/python-diamond/Diamond/blob/master/.travis.yml
* https://github.com/python-diamond/Diamond/pull/259

**Comment by rahul-gj** [comment]
Thank you.

**Comment by chhantyal** [comment]
There is some issue with updating the site, I will have a look as soon as possible.

**Comment by chhantyal** [comment]
Guess this issue is fixed http://py3readiness.org/
