### ISSUE TITLE
PyPi has removed top packages api, use Google BigQuery to get them

### ISSUE THREAD

**Issue by chhantyal** [chhantyal/py3readiness#53]
Use BigQuery to get data as suggested at https://packaging.python.org/guides/analyzing-pypi-package-downloads/

Alternatively, `pypinfo` can be used as well.

**Comment by maxim-lian** [comment]
Is this why newer packages aren't showing up? e.g. apache-beam is not listed

**Comment by hugovk** [comment]
Yes, the old PyPI API was removed in April, which is when this list stopped updating. 

See https://github.com/chhantyal/py3readiness/pull/51 for more info.

**Comment by chhantyal** [comment]
@maxim-lian though I doubit apache-beam is that popular to fall under 360 most popular package.

**Comment by hugovk** [comment]
apache-beam is at number 208:

https://hugovk.github.io/top-pypi-packages/

**Comment by anarcat** [comment]
the bigquery API has rate limits when you are not a paying customer (!) which might make this difficult.

**Comment by hugovk** [comment]
You get free quota which is enough, see https://github.com/chhantyal/py3readiness/issues/42 and https://github.com/chhantyal/py3readiness/pull/51.

**Comment by chhantyal** [comment]
Fixed in #51 , data is not included in repo. This issue is stale.
