### ISSUE TITLE
Fabric should be marked as supported

### ISSUE THREAD

**Issue by rostrovsky** [chhantyal/py3readiness#55]
Looks like Fabric is supported now:
https://pypi.org/project/Fabric/2.2.2/

**Comment by hugovk** [comment]
Duplicate of https://github.com/chhantyal/py3readiness/issues/54, please see https://github.com/chhantyal/py3readiness/issues/54#issuecomment-408772303 and https://github.com/chhantyal/py3readiness/pull/51.

**Comment by rostrovsky** [comment]
Sorry for duplicate. Closing issue in favour of #54.
