### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by vaibhavsagar** [chhantyal/py3readiness#6]
I notice the website hasn't been updated since the 29th of October. A new version of `caniusepython3` has been released and we should have at least 275 packages by now. Can you do an update, and is there any way I can help?

**Comment by Byron** [comment]
Good luck with that ! And thanks for the update - git-python is green now, which makes my day :) !

**Comment by chhantyal** [comment]
Ladies and gentlemen,

Auto-update (daily) should work now. Thanks for bearing patience.

**Comment by Byron** [comment]
Great to see, and thanks again for hosting the site !

You wouldn't believe what kind of psychological impact it made when I realised that [my project](https://github.com/gitpython-developers/GitPython) was in the top-300 packages. All of the sudden, I found the motivation to push it into the python 3 realm, and was happy when it finally turned green on the site :) !

**Comment by chhantyal** [comment]
wow that's very flattering comment ... I am glad that it made positive impact :)
