### ISSUE TITLE
Apache Beam supports Python 3 now

### ISSUE THREAD

**Issue by shoyer** [chhantyal/py3readiness#60]
As of v2.11.0 (released 10 days ago), Beam supports Python 3: https://pypi.org/project/apache-beam/

This will complete the list of the top 360 packages!

**Comment by hugovk** [comment]
Hooray!

See https://github.com/chhantyal/py3readiness/pull/61 to update the stats and https://hugovk.github.io/py3readiness/ for a preview.

The top-360 list has changed since the last update in November, and there's 4 new ones still to support Python 3.

**Comment by hugovk** [comment]
Of the four, at least https://github.com/benediktschmitt/py-filelock supports Python 3, it's just missing metadata (https://github.com/benediktschmitt/py-filelock/blob/master/setup.py#L61).

And it looks like https://github.com/dmlc/xgboost also supports Python 3, but is also missing metadata (https://github.com/dmlc/xgboost/blob/master/python-package/setup.py), see https://github.com/dmlc/xgboost/issues/4154, .

**Comment by shoyer** [comment]
nvidia-ml-py3 has py3 support in the name :)

**Comment by shoyer** [comment]
I find it a little hard to believe that people are still relying on the `oauth` library. It hasn't had a release since 2009: https://pypi.org/project/oauth/#history

**Comment by hugovk** [comment]
Downloads last month: 726,483

https://pypistats.org/packages/oauth

I'd imagine it's a dependency of dependencies for many projects.

The chart shows nearly 20% for Python 3, so sounds like it's supported (or works).

**Comment by hugovk** [comment]
Shall we close this? 

apache-beam is now green in http://py3readiness.org/
