### ISSUE TITLE
xgboost, py-filelock and nvidia-ml-py3 support python3

### ISSUE THREAD

**Issue by qsantos** [chhantyal/py3readiness#62]
Unless i am mistaken, [nvidia-ml-py3](https://pypi.org/project/nvidia-ml-py3/) and [py-filelock](https://github.com/benediktschmitt/py-filelock) support Python 3, according to their READMEs and [xgboost](https://xgboost.readthedocs.io/en/latest/build.html) according to its installation guide. This leaves [oauth](https://code.google.com/archive/p/oauth/), the later of which is archived, and thus might be considered dead anyway.

**Comment by hugovk** [comment]
```console
$ caniusepython3 --projects nvidia-ml-py3 filelock xgboost
Finding and checking dependencies ...

You need 3 projects to transition to Python 3.
Of those 3 projects, 3 have no direct dependencies blocking their transition:

  filelock
  nvidia-ml-py3
  xgboost
```

* The last filelock release is missing Trove classifiers https://pypi.org/project/filelock/ but they were merged in yesterday (https://github.com/benediktschmitt/py-filelock/pull/46). The next release should include them.

* The last nvidia-ml-py3 release is missing Trove classifiers https://pypi.org/project/nvidia-ml-py3/. Please can you ask them to update the classifiers, and/or open a PR or issue to add it to the caniusepython3 overrides list? https://github.com/brettcannon/caniusepython3#what-if-i-know-of-a-project-that-should-be-added-to-the-overrides-file

* Again, the last xgboost release is missing classifiers https://pypi.org/project/xgboost/. Please open a PR or issue with them to add classifiers, and/or overrides to caniusepython3 if there's evidence of the current PyPI version supporting Python 3.

**Comment by bstaletic** [comment]
The `oauth` is python2 only, but there's `oauth2` which is python3 only.

**Comment by CAM-Gerlach** [comment]
@hugovk ``filelock`` and ``xgboost`` have their classifiers pushed to PyPI, and ``Nvidia-ML-Py3`` has its override implemented in the released version of ``caniusepython3`` (per brettcannon/caniusepython3#202 ). Ergo, time to update the list, methinks?

**Comment by hugovk** [comment]
Please see PR https://github.com/chhantyal/py3readiness/pull/68 to update the stats.

Preview: https://hugovk.github.io/py3readiness/

Those three are now green and it's at 359/360!

Just oauth remaining.
