### ISSUE TITLE
Supervisor supports Python 3 now

### ISSUE THREAD

**Issue by cclauss** [chhantyal/py3readiness#63]

**Comment by hugovk** [comment]
Confirmed:

```console
$ caniusepython3 --projects Supervisor
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!
```

Although it's not in the last generated 360 (http://py3readiness.org) or an updated 360 (https://hugovk.github.io/py3readiness/).

It's currently at number 456 (https://hugovk.github.io/top-pypi-packages/).

**Comment by cclauss** [comment]
Sorry....  I was looking at  https://tiran.github.io/py3readiness
