### ISSUE TITLE
Need to update... Last update was six months ago

### ISSUE THREAD

**Issue by cclauss** [chhantyal/py3readiness#64]
Last updated on Sunday, 23 September 2018, 09:47:38  Would fix #60, #62, #63

**Comment by hugovk** [comment]
Maybe you have an old, cached version? I see:

> Last updated on Monday, 11 March 2019, 23:09:53

https://github.com/chhantyal/py3readiness/pull/61 was the last update.

Of those issues:

* #60 can be closed now
* #62 is still valid, `caniusepython3 --projects nvidia-ml-py3 filelock xgboost` still need updating, please do this upstream at caniusepython3
* #63 is currently invalid, Supervisor doesn't show up in the top 360

**Comment by cclauss** [comment]
Yes.  Sorry, I was looking at https://tiran.github.io/py3readiness which is really much close to what we should be showing these daze...  269 days until Python 2 end of life.
```python
from datetime import date
print((date(2020, 1, 1) - date.today()).days, "days until Python 2 end of life.")
```

**Comment by hugovk** [comment]
Python 2 progress bar: 92.22990099140084%

https://python2woop.pw

**Comment by hugovk** [comment]
http://py3readiness.org/ was updated this week. Can this be closed?

Good news! 360/360 are green!

**Comment by cclauss** [comment]
https://tiran.github.io/py3readiness still needs an update.
